---
# Different settings for environment


- name: Set environment variables
  lineinfile: dest=.bashrc
              line="export {{ item.name }}={{ item.value }}"
  with_items: "{{ env_vars }}"

- name: Setup aliases
  lineinfile: dest=.bashrc
              line="alias {{ item.name }}='{{ item.value }}'"
              state=present
  with_items: "{{ aliases }}"

- name: Set local timezone
  become: true
  command: timedatectl set-timezone Europe/Moscow
