---
# Install and setup fzf


- name: Clone fzf repository
  git: repo=https://github.com/junegunn/fzf.git
       dest=.fzf
       clone=yes
       depth=1

- name: Install fzf
  command: bash -ic "{{ ansible_env.HOME }}/.fzf/install --all --64"
