---
# Install and setup fzf


- name: Clone fzf repository
  git: repo=https://github.com/junegunn/fzf.git
       dest=.fzf
       clone=yes
       depth=1
       version={{ fzf_version }}

- name: Install fzf
  command: bash -ic "{{ ansible_env.HOME }}/.fzf/install --all --64"
  tags:
    # For some reason, I failed to register result of Clone fzf repository
    - skip_ansible_lint

- name: Use ag for fzf default command
  lineinfile: dest=.bashrc
              line='export FZF_DEFAULT_COMMAND="(ag --nocolor --nogroup -l -g \'\') 2> /dev/null"'
