---
# Install and setup support of gruvbox


- name: Clone gruvbox repository
  git: repo=https://github.com/morhetz/gruvbox.git
       dest=.gruvbox
       clone=yes
       depth=1

- name: Source gruvbox colors
  lineinfile: dest=.bashrc
              line='source "$HOME/.gruvbox/gruvbox_256palette.sh"'
              state=present
