---
# Specific development environment for Sergey Arkhipov
# sarkhipov@mirantis.com


- name: Install see
  become: true
  pip: name=see state=present

- include: dotfiles.yaml
- include: neovim.yaml
- include: tmux.yaml
- include: fzf.yaml
- include: gruvbox.yaml
- include: environment.yaml
- include: keychain.yaml

- name: Activate tmux with tmuxinator by default
  lineinfile: dest=.bashrc
              line='if [ -z "$TMUX" ]; then tmux a || mux start {{ venv }}; fi'
              state=present
