---
# tmux related stuff


- name: Download tmux with truecolor support
  get_url: url=http://ftp.ru.debian.org/debian/pool/main/t/tmux/tmux_2.2-3_amd64.deb
           dest=/tmp/tmux.deb

- name: Install tmux with truecolor support
  become: true
  apt: deb=/tmp/tmux.deb

- name: Add tmux plugin manager
  git: repo=https://github.com/tmux-plugins/tpm
       dest=.tmux/plugins/tpm
       clone=yes
       depth=1

- name: Ensure tmuxinator has config directory
  file: path=/home/{{ ansible_ssh_user }}/.tmuxinator state=directory

- name: Add tmuxinator config
  copy: src=tmuxinator.vsm.yaml dest=.tmuxinator/vsm.yml

- name: Activate tmux with tmuxinator by default
  lineinfile: dest=.bashrc
              line='if [ -z "$TMUX" ]; then tmux a || mux start vsm; fi'
              state=present
