---
# tmux related stuff


- name: Check tmux version
  command: tmux -V
  register: tmux_version
  tags:
    - skip_ansible_lint

- name: Download tmux with truecolor support
  get_url: url=http://ftp.ru.debian.org/debian/pool/main/t/tmux/tmux_2.3-4_amd64.deb
           dest=/tmp/tmux.deb
  when: tmux_version.stdout.find("2.2") == -1

- name: Install tmux with truecolor support
  become: true
  apt: deb=/tmp/tmux.deb
  when: tmux_version.stdout.find("2.2") == -1

- name: Add tmux plugin manager
  git: repo=https://github.com/tmux-plugins/tpm
       dest=.tmux/plugins/tpm
       clone=yes
       depth=1
       version=master

- name: Ensure tmuxinator has config directory
  file: path=/home/{{ ansible_ssh_user }}/.tmuxinator state=directory

- name: Add tmuxinator config
  template: src=tmuxinator.proj.yaml.j2 dest=.tmuxinator/{{ venv }}.yml
