---
# APT tasks for crocbilling development environment.


- name: Ensure sources.list is correct
  become: true
  copy: src=apt.sources.list dest=/etc/apt/sources.list

- name: Update packagaes
  become: true
  command: apt-get -yqq update warn=no
  tags:
    # This is to activate apt module :(
    - skip_ansible_lint

- name: Install aptitude
  become: true
  command: apt-get install -yqq aptitude warn=no
  tags:
    # This is to activate apt module :(
    - skip_ansible_lint

- name: Update host packages to the latest versions
  become: true
  apt: update_cache=yes upgrade=safe

- name: Ensure mandatory APT packages are installed
  become: true
  apt: name="{{ item }}" state=present
  with_items: "{{ apt_packages }}"

- name: Update pip
  become: true
  pip: name=pip
       state=latest
       executable={{ item }}
  with_items:
    - /usr/bin/pip2
    - /usr/bin/pip3
  tags:
    - skip_ansible_lint

- name: Update setuptools
  become: true
  pip: name=setuptools
       state=latest
       executable={{ item }}
  with_items:
    - /usr/bin/pip2
    - /usr/bin/pip3
  tags:
    - skip_ansible_lint

- name: Remove unwanted provisioners
  become: true
  apt: name="{{ item }}" state=absent purge=yes
  with_items: "{{ unwanted_apt_packages }}"

- name: Remove crap
  become: true
  command: apt-get autoremove -y
  tags:
    # It is ok to run it a lot
    - skip_ansible_lint

- name: Install ansible
  become: true
  apt: name=ansible state=present
