---
# Copyright (c) 2016 Mirantis Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: Ensure sources.list is correct
  become: true
  copy: src=apt.sources.list dest=/etc/apt/sources.list

- name: Update packagaes
  become: true
  command: apt-get -yqq update warn=no
  tags:
    # This is to activate apt module :(
    - skip_ansible_lint

- name: Install aptitude
  become: true
  command: apt-get install -yqq aptitude warn=no
  tags:
    # This is to activate apt module :(
    - skip_ansible_lint

- name: Update host packages to the latest versions
  become: true
  apt: update_cache=yes upgrade=safe

- name: Ensure mandatory APT packages are installed
  become: true
  apt: name="{{ item }}" state=present
  with_items: "{{ apt_packages }}"

- name: Update pip
  become: true
  pip: name=pip
       state=latest
       executable={{ item }}
  with_items:
    - /usr/bin/pip2
    - /usr/bin/pip3
  tags:
    - skip_ansible_lint

- name: Update setuptools
  become: true
  pip: name=setuptools
       state=latest
       executable={{ item }}
  with_items:
    - /usr/bin/pip2
    - /usr/bin/pip3
  tags:
    - skip_ansible_lint

- name: Remove unwanted provisioners
  become: true
  apt: name="{{ item }}" state=absent purge=yes
  with_items: "{{ unwanted_apt_packages }}"

- name: Remove crap
  become: true
  command: apt-get autoremove -y
  tags:
    # It is ok to run it a lot
    - skip_ansible_lint

- name: Install ansible
  become: true
  apt: name=ansible state=present
