---
# Common bashrc stuff

- name: Ensure PATH is correct
  lineinfile: dest=.bashrc
              regexp="^export PATH"
              line="export PATH=$HOME/.local/bin:$PATH"
              state=present

- name: Ensure proper prompt is set
  blockinfile:
    dest: .bashrc
    marker: "# {mark} ANSIBLE MANAGED PROMPT BLOCK"
    block: |
      RED="\[\033[0;31m\]"
      YELLOW="\[\033[0;33m\]"
      GREEN="\[\033[0;32m\]"
      BLUE="\[\033[1;34m\]"
      NO_COLOUR="\[\033[0m\]"
      CYAN="\[\033[0;36m\]"
      PURPLE="\[\033[0;35m\]"

      prompt_cmd () {
          PS1="$YELLOW\w$NO_COLOUR (git:$BLUE$(git branch 2>/dev/null | grep '^*' | colrm 1 2)$NO_COLOUR) (venv:$GREEN$(pyenv version-name)$NO_COLOUR): "
      }

      PROMPT_COMMAND=prompt_cmd

- name: Copy terminfo for tmux to support italic
  copy: src=tmux-256color-italic dest=/tmp/tmux-italic

- name: Add italic terminfo for tmux
  shell: tic /tmp/tmux-italic

- name: Ensure proper tmux term is set
  blockinfile:
    dest: .bashrc
    marker: "# {mark} ANSIBLE MANAGED TMUX BLOCK"
    block: |
      if [ -n "$TMUX" ]; then
          export TERM=tmux-256color-italic
      else
          export TERM=xterm-256color
      fi
