---
# Copyright (c) 2016 Mirantis Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: Copy example keys
  command: make copy_example_keys chdir=/vagrant creates=/vagrant/ubuntu_apt.list
  tags:
    - skip_ansible_lint

- name: Copy ubuntu repo as a source for container build
  copy:
    src: apt.sources.list
    dest: /vagrant/ubuntu_apt.list

- name: Build containers
  become: true
  command: >
    make -j {{ ansible_processor_count }}
    build_containers build_container_ui_tests build_container_test_keystone
    chdir=/vagrant
  tags:
    - skip_ansible_lint
