---
# Base tasks for CephLCM development provision


- include: apt.yaml
- include: locale.yaml
- include: htop.yaml
- include: ssh.yaml
- include: docker.yaml
- include: nodejs.yaml
- include: bashrc.yaml
