---
# NodeJS and UI related stuff


- name: Install node 7x repository
  become: true
  shell: "curl -sL {{ node_install_script }} | bash -"

- name: Install nodejs
  become: true
  apt: name=nodejs state=present

- name: Install UI dependencies
  npm: path=/vagrant/ui
