---
version: "2"
services:
  frontend:
    image: shrimp-frontend
    links:
      - api
      - cron
    ports:
      - "9999:80"
      - "10000:443"
    restart: always
  api:
    image: shrimp-api
    links:
      - database
    restart: "on-failure:5"
  controller:
    image: shrimp-controller
    links:
      - database
    restart: "on-failure:5"
  database:
    image: shrimp-db
    volumes_from:
      - database_data
    restart: always
  database_data:
    image: shrimp-db-data
    volumes:
      - /data/db
  cron:
    image: shrimp-cron
    links:
      - database
    restart: "on-failure:3"
