---
version: "2"
services:
  frontend:
    image: "${DECAPOD_REGISTRY_URL}${DECAPOD_NAMESPACE}decapod/frontend:${DECAPOD_VERSION}"
    links:
      - api
      - cron
    ports:
      - "${DECAPOD_HTTP_PORT}:80"
      - "${DECAPOD_HTTPS_PORT}:443"
    restart: always
  api:
    image: "${DECAPOD_REGISTRY_URL}${DECAPOD_NAMESPACE}decapod/api:${DECAPOD_VERSION}"
    links:
      - database
    restart: "on-failure:5"
  controller:
    image: "${DECAPOD_REGISTRY_URL}${DECAPOD_NAMESPACE}decapod/controller:${DECAPOD_VERSION}"
    links:
      - database
    restart: "on-failure:5"
  database:
    image: "${DECAPOD_REGISTRY_URL}${DECAPOD_NAMESPACE}decapod/db:${DECAPOD_VERSION}"
    volumes_from:
      - database_data
    restart: always
  database_data:
    image: "${DECAPOD_REGISTRY_URL}${DECAPOD_NAMESPACE}decapod/db-data:${DECAPOD_VERSION}"
    volumes:
      - /data/db
  cron:
    image: "${DECAPOD_REGISTRY_URL}${DECAPOD_NAMESPACE}decapod/cron:${DECAPOD_VERSION}"
    links:
      - database
    restart: "on-failure:3"
