---
# Provision for Shrimp project development environment


- name: Setup development environment
  hosts: all
  environment:
    LANG: C
    LC_ALL: C
    LC_MESSAGES: C
    LC_CTYPE: C
    TMUX: 1
  vars:
    venv: shrimp
  roles:
    - base
    - python
    - role: mongodb
      in_memory: true
    - role: sarkhipov
      when: lookup("env", "DEV") == "sarkhipov"
