version: "2"
services:
  api:
    build:
      context: ../
      dockerfile: devenv/dev.dockerfile
    command: cephlcm-api
    links:
      - database
  controller:
    build:
      context: ../
      dockerfile: devenv/dev.dockerfile
    command: cephlcm-controller start
    cap_add:
      - ALL
    pid: "host"
    links:
      - database
  frontend:
    build:
      context: .
      dockerfile: caddy.dockerfile
    links:
      - api
    ports:
      - "9999:80"
  database:
    image: mongo:3.2
