---
# Copyright (c) 2017 Mirantis Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- include: "{{ decapod_common_playbooks }}/init.yaml"
  when: decapod_initialized | default(false) | bool

- include: "{{ decapod_common_playbooks }}/tasks/set_ceph_facts.yaml"

- set_fact:
    osd_retry_attempts: "{{ (osd | default(decapod_vars.osd)).retry_attempts }}"
    osd_retry_delay: "{{ (osd | default(decapod_vars.osd)).retry_delay }}"

- name: Restart OSD item
  service:
    name: "ceph-osd@{{ osd_number }}"
    state: restarted
    sleep: 10

- name: wait for PGs to become active+clean
  command: ceph --cluster "{{ cluster }}" -s --format json
  register: ceph_health_post
  until: >
    ((ceph_health_post.stdout | from_json).pgmap.pgs_by_state | length) == 1
    and
    (ceph_health_post.stdout | from_json).pgmap.pgs_by_state.0.state_name == "active+clean"
  retries: "{{ osd_retry_attempts }}"
  delay: "{{ osd_retry_delay }}"
