---
# Copyright (c) 2017 Mirantis Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: Check user-data exists
  local_action: stat path="{{ user_data | mandatory }}"

- name: Update APT cache
  become: true
  command: apt-get update warn=no

- name: Install requirements
  command: apt-get install "{{ item }}"
  become: true
  with_items:
    - python-apt


- include: with-cloud-init.yaml
  when: cloud_init | bool

- include: without-cloud-init.yaml
  when: not (cloud_init | bool)
