# This is a default config for CephLCM tool
#
# It is implemented as TOML
# https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md
#
# It has all options you may find useful. If you want to redefine something,
# just set required options, all other options would be taken from previous
# config in load order. This config is always first.
#
# Load order is:
# - This file
# - /etc/cephlcm/config.toml
# - $HOME/.config/cephlcm/config.toml (or $XDG_CONFIG_HOME/cephlcm/config.toml)
# - ~/.cephlcm.toml
# - $(pwd)/cephlcm.toml

# API specific settings
# Options here are Flask options so please check
# http://flask.pocoo.org/docs/0.11/config/#builtin-configuration-values
[api]
debug = true
testing = false
logger_name = "cephlcm.api.wsgi"
logger_handler_policy = "never"
json_sort_keys = true
jsonify_prettyprint_regular = true
json_as_ascii = false

# Setup for Flask-PyMongo
# https://flask-pymongo.readthedocs.io/en/latest/
[api.mongo]
host = "127.0.0.1"
port = 27017
dbname = "devel"
connect = false

# API options related to tokens
[api.token]
# Default TTL for token in seconds
ttl_in_seconds = 120

# Common options
[common]
# Default length of the generated passwords
password_length = 10

[common.email]
# Default email in FROM field
from = "noreply@mirantis.com"
# Default SMTP host
host = "localhost"
# Default SMTP port
port = 25
# Default SMTP login (set to "" if no auth is required)
login = ""
# Default SMTP password (set to "" if no auth is required)
password = ""

# Default Python logging is used.
# https://docs.python.org/2/library/logging.config.html#dictionary-schema-details
[common.logging]
version = 1
incremental = false
disable_existing_loggers = true

[common.logging.root]
handlers = []

[common.logging.filters]

[common.logging.formatters.debug]
format = "%(asctime)s [%(levelname)-8s] (%(filename)15s:%(lineno)-4d): %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[common.logging.formatters.default]
format = "%(asctime)s [%(levelname)-8s]: %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[common.logging.formatters.syslog]
format = "%(name)s %(asctime)s [%(levelname)-8s]: %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[common.logging.handlers.debug]
class = "logging.StreamHandler"
formatter = "debug"
level = "DEBUG"

[common.logging.loggers.cephlcm]
propagate = true
level = "DEBUG"
handlers = ["debug"]

# Settings for plugins
[plugins.alerts.email]
enabled = false
send_to = ["bigboss@example.com"]
from = "errors@example.com"
