heat_template_version: 2013-05-23
description: Template for Whale system tests

parameters:
  instance_type:
    type: string
    label: Instance Type
    description: Type of flavor to use
    constraints:
      - allowed_values:
        - m1.small
        - m1.medium
        - m1.large
  image_id:
    type: string
    label: Image
    description: Image ID to use for VMs (should be Ubuntu Xenial)
  volume_size:
    type: number
    label: Volume Size
    description: Size of volume in GBs
    default: 5
    constraints:
      - range: {min: 1, max: 1024}
  volume_type:
    type: string
    label: Type of volume
    description: Type of volumes to create and attach to VMs.
  instance_count:
    type: number
    label: Amount of instances
    description: Amount of instances per instance
    default: 5
    constraints:
      - range: {min: 1, max: 1024}
  network:
    type: string
    label: Network to use
    description: Network to use for instances
  floating_network:
    type: string
    label: Floating IP network
    description: The name of the network which will be used for pooling.

resources:
  ceph_hosts:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: instance_count}
      resource_def:
        type: server_with_volumes.yaml
        properties:
          volume_size: {get_param: volume_size}
          volume_type: {get_param: volume_type}
          image_id: {get_param: image_id}
          instance_type: {get_param: instance_type}
          network: {get_param: network}
          floating_network: {get_param: floating_network}

outputs:
  host_ips:
    description: Floating IPs of created hosts
    value: {get_attr: [ceph_hosts, host_ip]}
