parameters:
  instance_type: m1.small
  image: xenial-server-cloudimg-amd64-disk1
  volumes_per_instance: 3
  volume_size: 2
  instance_count: 5
  network: jenkins_ci_internal
  floating_network: admin_floating_net
  volume_type: volumes_ceph
