parameters:
  instance_type: m1.small
  image_id: b7b8c4b4-64af-48aa-8d9e-d82540f9a278
  volume_size: 2
  instance_count: 5
  network: jenkins_ci_internal
  floating_network: admin_floating_net
  volume_type: volumes_ceph
