heat_template_version: 2013-05-23

parameters:
  instance_type:
    type: string
    label: Instance Type
    description: Type of flavor to use
    constraints:
      - allowed_values:
        - m1.small
        - m1.medium
        - m1.large
  image:
    type: string
    label: Image
    description: Image to use for VMs (should be Ubuntu Xenial)
  volumes_per_instance:
    type: number
    label: Volume count
    description: Amount of volumes to attach per instance
    default: 5
    constraints:
      - range: {min: 1, max: 1024}
  volume_size:
    type: number
    label: Volume Size
    description: Size of volume in GBs
    default: 5
    constraints:
      - range: {min: 1, max: 1024}
  network:
    type: string
    label: Network to use
    description: Network to use for instances
  public_ip_pool_name:
    type: string
    label: Floating IP pool
    description: The name of the pool with floating IPs to assign

resources:
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: {get_param: public_ip_pool_name}
  floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: {get_resource: floating_ip}
      server_id: {get_resource: ceph_host}
  ceph_host:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: instance_type}
      networks:
        - network: {get_param: network}
      user_data: {get_file: 'user-data.txt'}
      user_data_format: RAW
  ceph_volumes:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: volumes_per_instance}
      resource_def:
        type: volume_with_attachment.yaml
        properties:
          volume_size: {get_param: volume_size}
          instance_id: {get_resource: ceph_host}

outputs:
  host_ip:
    description: Floating IP of the host
    value: {get_attr: [floating_ip, floating_ip_address]}
