heat_template_version: 2013-05-23

parameters:
  volume_size:
    type: number
    label: Volume Size
    description: Size of volume in GBs
    default: 5
    constraints:
      - range: {min: 1, max: 1024}
  instance_id:
    type: string
    label: ID of the instance to attach to
    description: Type of flavor to use

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      size: {get_param: volume_size}
  attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: {get_resource: volume}
      instance_uuid: {get_param: instance_id}
