---
# Playbook for mongodb installation


- name: Add APT key
  become: true
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id="{{ repo_key }}"

- name: Add repository
  become: true
  apt_repository: repo="deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
                  state=present

- name: Put db files on tmpfs
  become: true
  mount: name={{ db_path }}
         src="tmpfs"
         fstype=tmpfs
         opts="nodev,noatime,nodiratime,noexec,size={{ (ansible_memtotal_mb * 0.3)|int|abs }}M"
         state=mounted
  when: in_memory

- name: Install mongodb
  become: true
  apt: name="{{ item }}={{ mongodb_version }}" update_cache=yes
  with_items: "{{ mongodb_components }}"
  register: mongo_installed

- name: Pin mongodb versions
  become: true
  command: apt-mark hold "{{ item }}"
  with_items: "{{ mongodb_components }}"
  when: mongo_installed.changed

- name: Install SystemD script
  become: true
  copy: src=mongodb.service dest=/etc/systemd/system/mongodb.service
  register: script_result

- name: Install mongodb config
  become: true
  template: src=mongod.conf.j2 dest=/etc/mongod.conf

- name: Enable mongodb service
  become: true
  command: systemctl enable mongodb.service
  when: script_result.changed

- name: Restart mongodb service
  become: true
  command: systemctl restart mongodb.service
  when: script_result.changed
