---
# Copyright (c) 2016 Mirantis Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

stow_dotfiles:
  - ag
  - aria2
  - ctags
  - git
  - nodejs
  - python
  - scripts
  - tmux
  - vim

aliases:
  g: git
  v: nvim
  vim: nvim
  mkdir: mkdir -pv
  gst: g s
  gs: g s
  gdf: g df
  t: tig
  ta: tig --all
  ag: ag --color -fS
  dc: docker-compose -f /vagrant/docker-compose.yml -p decapod
  dcd: docker-compose -f /vagrant/docker-compose.yml -f /vagrant/docker-compose.dev.yml -p decapod

oneliners:
  dal: dcd exec -T admin decapod execution log "$1" | less
  dam: dcd exec -T admin decapod-admin migration apply
  dab: dcd exec admin bash

env_vars:
  NVIM_TUI_ENABLE_CURSOR_SHAPE: 1
  NVIM_TUI_ENABLE_TRUE_COLOR: 1
  EDITOR: nvim
  PYTHONSTARTUP: $HOME/.pythonrc
  DECAPOD_URL: http://127.0.0.1:9999
  DECAPOD_LOGIN: root
  DECAPOD_PASSWORD: root
