[db]
uri = "mongodb://database:27017/cephlcm"

[controller]
ansible_config = "/ansible.cfg"

[api]
debug = false
json_sort_keys = false
jsonify_prettyprint_regular = false

[common]
bcrypt_rounds = 12
