---
# Install Python dependencies


- name: Ensure PIP config directory is created
  become: true
  file: path=.config/pip state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}

- name: Ensure pip.conf is up to date
  copy: src=pip.conf dest=.config/pip/pip.conf

- name: Install tox
  become: true
  pip: name=tox
       state=present
       executable=pip3
       version={{ tox_version }}
