---
# Copyright (c) 2016 Mirantis Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: Install packages, required to build Pythons
  become: true
  apt: name="{{ item }}" state=present
  with_items: "{{ build_requirements }}"

- name: Clone PyEnv repository
  git: repo=https://github.com/yyuu/pyenv.git
       dest="{{ pyenv_root }}"
       depth=1
       clone=yes
       version=master

- name: Ensure PYENV_ROOT is correct
  lineinfile: dest=.bashrc
              line="export PYENV_ROOT=$HOME/{{ pyenv_root }}"
              state=present

- name: Ensure PATH is correct
  lineinfile: dest=.bashrc
              insertafter="^export PYENV_ROOT"
              line='export PATH="$PYENV_ROOT/bin:$PATH"'
              state=present

- name: Ensure that PyEnv is initialized
  lineinfile: dest=.bashrc
              line='eval "$(pyenv init -)"'
              state=present
