---
# Install Pythons in Pyenv and create CephLCM virtualenv


- name: Install Pythons
  command: bash -ic "pyenv install -s {{ item }}"
  with_items: "{{ pyenv_pythons }}"

- name: Check if CephLCM virtualenv exists
  stat: path="{{ pyenv_root }}/versions/cephlcm"
  register: cephlcm_virtualenv

- name: Create CephLCM virtualenv
  command: bash -ic "pyenv virtualenv {{ cephlcm_python }} {{ venv }}"
  when: not cephlcm_virtualenv.stat.exists

- name: Install CephLCM requirements
  command: bash -ic "pyenv activate {{ venv }} && pip install -r requirements.txt -r test-requirements.txt -r optional-requirements.txt -e ."
          chdir=/vagrant
