---
# Copyright (c) 2016 Mirantis Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: Install Pythons
  command: bash -ic "pyenv install -s {{ item }}"
  with_items: "{{ pyenv_pythons }}"
  tags:
    # -s flags for pyenv install tells that it skips if nothing to do
    - skip_ansible_lint

- name: Check if Decapod virtualenv exists
  stat: path="{{ pyenv_root }}/versions/decapod"
  register: decapod_virtualenv

- name: Create Decapod virtualenv
  command: bash -ic "pyenv virtualenv {{ decapod_python }} {{ venv }}"
  when: not decapod_virtualenv.stat.exists

- name: Install requirements in PyEnv virtualenv
  command: bash -ic "pyenv activate {{ venv }} && pip install -r {{ item }} -c constraints.txt"
           chdir=/vagrant
  with_items:
    - build-requirements.txt
    - test-requirements.txt
    - optional-requirements.txt
  tags:
    # This is to update requirements
    - skip_ansible_lint

- name: Update PyEnv virtualenv
  command: bash -ic "pyenv activate {{ venv }} && pip install -e {{ item }} -c constraints.txt"
           chdir=/vagrant
  with_items:
    - backend/common
    - 'backend/api[keystone]'
    - backend/controller
    - decapodlib
    - 'backend/admin[uvloop]'
    - plugins/alerts/emails
    - plugins/playbook/server_discovery
    - plugins/playbook/playbook_helloworld
    - plugins/playbook/add_mon
    - plugins/playbook/add_osd
    - plugins/playbook/cinder_integration
    - plugins/playbook/deploy_cluster
    - plugins/playbook/purge_cluster
    - plugins/playbook/purge_telegraf
    - plugins/playbook/remove_osd
    - plugins/playbook/telegraf_integration
    - 'decapodcli[color,yaql,jq,jmespath]'
  tags:
    # This is to update requirements
    - skip_ansible_lint

- name: Ensure that shortcut for PyEnv virtualenv is installed
  lineinfile: dest=.bashrc
              line="alias ve='pyenv activate {{ venv }}'"
              state=present
