---
# Install Pythons in Pyenv and create Shrimp virtualenv


- name: Install Pythons
  command: bash -ic "pyenv install -s {{ item }}"
  with_items: "{{ pyenv_pythons }}"
  tags:
    # -s flags for pyenv install tells that it skips if nothing to do
    - skip_ansible_lint

- name: Check if Shrimp virtualenv exists
  stat: path="{{ pyenv_root }}/versions/shrimp"
  register: shrimp_virtualenv

- name: Create Shrimp virtualenv
  command: bash -ic "pyenv virtualenv {{ shrimp_python }} {{ venv }}"
  when: not shrimp_virtualenv.stat.exists

- name: Install requirements in PyEnv virtualenv
  command: bash -ic "pyenv activate {{ venv }} && pip install -r {{ item }} -c constraints.txt"
           chdir=/vagrant
  with_items:
    - build-requirements.txt
    - test-requirements.txt
    - optional-requirements.txt
  tags:
    # This is to update requirements
    - skip_ansible_lint

- name: Update PyEnv virtualenv
  command: bash -ic "pyenv activate {{ venv }} && pip install -e {{ item }} -c constraints.txt"
           chdir=/vagrant
  with_items:
    - backend/common
    - backend/api
    - backend/controller
    - backend/migration
    - plugins/alerts/emails
    - plugins/playbook/server_discovery
    - plugins/playbook/playbook_helloworld
  tags:
    # This is to update requirements
    - skip_ansible_lint

- name: Ensure that shortcut for PyEnv virtualenv is installed
  lineinfile: dest=.bashrc
              line="alias ve='pyenv activate {{ venv }}'"
              state=present
