---
# Install Pythons in Pyenv and create CephLCM virtualenv


- name: Install Pythons
  command: bash -ic "pyenv install -s {{ item }}"
  with_items: "{{ pyenv_pythons }}"
  tags:
    # -s flags for pyenv install tells that it skips if nothing to do
    - skip_ansible_lint

- name: Check if CephLCM virtualenv exists
  stat: path="{{ pyenv_root }}/versions/cephlcm"
  register: cephlcm_virtualenv

- name: Create CephLCM virtualenv
  command: bash -ic "pyenv virtualenv {{ cephlcm_python }} {{ venv }}"
  when: not cephlcm_virtualenv.stat.exists

- name: Install CephLCM requirements
  command: bash -ic "pyenv activate {{ venv }} && pip install -r requirements.txt -r test-requirements.txt -r optional-requirements.txt -c constraints.txt -e ."
          chdir=/vagrant
  tags:
    # This is to update requirements
    - skip_ansible_lint

- name: Install CephLCM plugins
  command: bash -ic "pyenv activate {{ venv }} && pip install -e ."
          chdir=/vagrant/playbook_plugins/{{ item }}
  with_items:
    - server_discovery
    - playbook_helloworld
  tags:
    # This is to update requirements
    - skip_ansible_lint

- name: Ensure that shortcut for PyEnv virtualenv is installed
  lineinfile: dest=.bashrc
              line="alias ve='pyenv activate {{ venv }}'"
              state=present
